#
# This file is currently used ONLY to configure the Black formatter tool.
# As the time of this writing it is the only tool used in the project that only supports .toml config file format.
# All the rest of the configuration for the tools used in this project is place
# in the setup.cfg file. This file currently only exists for the management of Black configuration parameters.
#

[tool.black]
verbose = 1
line-length = 120
# --check and diff options are commented in order to provide them over the command line, to make invocation more flexible
# and being able to execute format checks and auto-formatting with two different commands.
#--check = "yes"
#diff = "y"
color = true
target-version = ["py38"]